### ISSUE TITLE
get Error "RuntimeError: The weights trying to be saved contained shared tensors"

### ISSUE THREAD

**Issue by CynthiaChuang** [2U1/Phi3-Vision-Finetune#14]
I set the following parameters and executed finetune.sh
```
--bf16 False \
--tf32 False \
--disable_flash_attn2 True
```

But I encountered the following error when saving checkpoint

```
  File "/work/aa1600161/Phi3-Vision-ft-0716/src/training/trainer.py", line 131, in _save
    super(Phi3VTrainer, self)._save(output_dir, state_dict)
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 3500, in _save
    self.model.save_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 2616, in save_pretrained
    raise RuntimeError(
RuntimeError: The weights trying to be saved contained shared tensors [{'model.vision_embed_tokens.wte.weight', 'model.embed_tokens.weight'}] that are mismatching the transformers base configuration. Try saving using `safe_serialization=False` or remove this tensor sharing.
```

**Comment by 2U1** [comment]
@CynthiaChuang For temporary fix, you could change the trainer class.
https://github.com/2U1/Phi3-Vision-ft/blob/960cb9cddf089599b0443f20b44e8fda226a8a5c/src/training/trainer.py#L127-L128

comment the `super(Phi3VTrainer, self)._save_checkpoint(model, trial, metrics)` line and use `pass`.

I'll make it work asap.

Thanks for reporting.

**Comment by CynthiaChuang** [comment]
I'll download it and give it a try, and I'll report back to you later.

**Comment by 2U1** [comment]
Closing the issue for solved issue.

https://github.com/2U1/Phi3-Vision-Finetune/issues/15#issue-2431532353

**Comment by CynthiaChuang** [comment]
Sorry, due to the windstorm disaster in my area, I have been unable to complete the test.

Today, after running the test, the program completed successfully without encountering the same error message. If there are any further issues, I will reach out to you. Thank you!

**Comment by 2U1** [comment]
@CynthiaChuang Thanks for your interest! Always welcome and appreciate reporting other issues. If you need any further adjustments, feel free to ask!
