### ISSUE TITLE
Problem with full fine tune 

### ISSUE THREAD

**Issue by WYY220062** [2U1/Phi3-Vision-Finetune#15]
Hi! I do the full fine tune with 30 epochs.
But at around 20 epochs, I have this error, and the processes are killed.
`RuntimeError: The weights trying to be saved contained shared tensors [{'model.vision_embed_tokens.wte.weight', 'model.embed_tokens.weight'}] that are mismatching the transformers base configuration. Try saving using `safe_serialization=False` or remove this tensor sharing.`
Do you have any idea on this?

Should I change the code `trainer.model.config.save_pretrained(output_dir)` in train_utils.py to `trainer.model.config.save_pretrained(output_dir, safe_serialization=False)`?

**Comment by 2U1** [comment]
@WYY220062 Sorry for the inconvinience. I think it is caused by saving checkpoint. 
I've fixed the code by removing the shared tensor when saving. Can you use the latest code for training?

**Comment by WYY220062** [comment]
The new version works, thank you for your great work.
