### ISSUE TITLE
Resume_from_checkpoint 

### ISSUE THREAD

**Issue by CynthiaChuang** [2U1/Phi3-Vision-Finetune#16]
Recently, I needed to resume training, so I added the following code to `train.py`:

I added `import pathlib` at line 16 and replaced `trainer.train()` at line 192 with:

```python=
if list(pathlib.Path(training_args.output_dir).glob("checkpoint-*")):
    trainer.train(resume_from_checkpoint=True)
else:
    trainer.train()
```

When executing training, set the `model_id` to the checkpoint folder where you want to continue training and the `output_dir` to its parent folder.

I hope this helps those who need it.

**Comment by 2U1** [comment]
@CynthiaChuang Thanks for the issue. I'll add resuming from checkpoint soon. I really appriciate this.

**Comment by 2U1** [comment]
I've added the auto resume code. Thank you.
