### ISSUE TITLE
Is it possible to disable fine-tuning for the LLM?

### ISSUE THREAD

**Issue by CynthiaChuang** [2U1/Phi3-Vision-Finetune#25]
hi, 2U1

I read your post on [Huggingface](https://huggingface.co/microsoft/Phi-3.5-vision-instruct/discussions/24), and you mentioned that I can _select each module (Vision, LLM, Projector) for fine-tuning_. I’m curious, does this mean I can also choose whether to fine-tune the LLM? If I want to disable fine-tuning for the language model, is that possible?

**Comment by 2U1** [comment]
@CynthiaChuang Yes you could. However I think I haven't yet set the parameters for that. I'll add that right away.

**Comment by 2U1** [comment]
@CynthiaChuang I've added a option for freezing the LLM too. 
However it should work only on disalbing LoRA(Including vision_model LoRa).

**Comment by CynthiaChuang** [comment]
@2U1 I just looked into your newly implemented feature. May I ask why you only modified `lm_head` and `model.layers` without adjusting `model.embed_tokens`?


![image](https://github.com/user-attachments/assets/7b3f26ee-a584-476a-8106-74dd8c20690a)

**Comment by 2U1** [comment]
@CynthiaChuang Oh, it was my mistake. Thanks for letting me know.
I've fixed it.

**Comment by 2U1** [comment]
I've fixed some other code to properly freeze the llm.

**Comment by 2U1** [comment]
Closing the issue for no other comments.
