### ISSUE TITLE
Padding_idx must be within num_embeddings #12

### ISSUE THREAD

**Issue by LJQbiu** [2U1/Phi3-Vision-Finetune#29]
The error message I encountered during training is: "assert padding_idx < weight.size(0), 'Padding_idx must be within num_embeddings'".
And after loading the pre-trained weights, the relevant layers of the model became like this. I'm wondering what this is related to?
I run finetune.sh
![image](https://github.com/user-attachments/assets/56e6d033-0f83-4cc5-9014-fba419cf13df)
![image](https://github.com/user-attachments/assets/50a20dfa-0ab2-48f0-98a4-63f4b5b55406)
![image](https://github.com/user-attachments/assets/7dda8e48-2f55-4bb4-8dda-fed011e1ece0)

**Comment by 2U1** [comment]
What you've showed me is from lora finetuning. If you are running full finetuning, the model should not have base_model.

**Comment by LJQbiu** [comment]
Thank you for your reply, and looking forward to more outstanding work in the future.
