### ISSUE TITLE
Image Token Indexing Starts from 0 Instead of 1

### ISSUE THREAD

**Issue by jaewon4** [2U1/Phi3-Vision-Finetune#30]
### Issue Description
When running the CLI demo, the model throws an assertion error because image tokens are indexed starting from 0, but the Phi3-Vision model requires image tokens to start from 1.

### Current Code
https://github.com/2U1/Phi3-Vision-Finetune/blob/ee2494017b6a5045316a3878926c7d1752fc3676/src/serve/cli.py#L94

### Solution
```
# cli.py
if image_list is not None and len(messages) < 2:
    for i in range(len(image_list)):
        placeholder += f"<|image_{i+1}|>\n"  # Image tokens now start from 1
```

**Comment by 2U1** [comment]
@jaewon4 Thanks for the issue, I wasn't using the CLI inference much so I didn't notice it. I've fixed and updated it.
