### ISSUE TITLE
Finetuning text and image

### ISSUE THREAD

**Issue by gaussiangit** [2U1/Phi3-Vision-Finetune#33]
How can we finetune text + image together ?

**Comment by 2U1** [comment]
Do you mean some data only have text and some has text+image?

**Comment by gaussiangit** [comment]
@2U1 Correct. Like Multi modal training ?!

**Comment by 2U1** [comment]
Actually phi3-vision is a multi-modal model.
However, I'm not really sure that this model can handle mixed modality dataset, something like I mentioned above. You could try only a dataset that contains text or text+image.

**Comment by gaussiangit** [comment]
@2U1 I would like to only finetune on image data. Should I use finetune.sh with freeze_llm=True or finetune_lora_vision.sh ?

**Comment by gaussiangit** [comment]
Much thanks
