### ISSUE TITLE
AttributeError: 'Phi3VProcessor' object has no attribute 'chat_template'

### ISSUE THREAD

**Issue by leonbora167** [2U1/Phi3-Vision-Finetune#34]
After any kind of finetuning, getting this error. The adapter weights are being stored but not sure whether this error is preventing any kind of issue for the fine tuning as such.
![image](https://github.com/user-attachments/assets/6bde8772-f1cb-4e38-98ef-d18898b2b74f)

**Comment by 2U1** [comment]
Sorry for the issue, seems like updating the transformer package it has been changed.
I'll fix the code soon.

**Comment by leonbora167** [comment]
Able to finetune without any issues now. Thank you so much. Will be closing this issue.
