### ISSUE TITLE
AssertionError: Padding_idx must be within num_embeddings 

### ISSUE THREAD

**Issue by golrokhme** [2U1/Phi3-Vision-Finetune#37]
getting error AssertionError: Padding_idx must be within num_embeddings 
using both finetune.sh and fintune_8bit.sh on both models (phi3 and phi 3.5)

**Comment by 2U1** [comment]
Are you using a mixed modality data?

**Comment by golrokhme** [comment]
Issue was with transformer version downgraded to 4.41.2 and resolved
